name: cuda-samples # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '12.6' # just for humans, typically '1.2+git' or '1.3.2'
summary: Cuda sample applications provided by nvidia # 79 char long summary
description: |
  This snap packages the cuda sample applications in order to test the
  behaviour of the GPU

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

package-repositories:
  - type: apt
    components: [main]
    suites: [r36.4]
    key-id: 3C6D1FF3100C8C3ABB0869C0E6543461A9996195
    key-server: https://repo.download.nvidia.com/jetson/jetson-ota-public.asc
    url: https://repo.download.nvidia.com/jetson/t234
    architectures: [arm64]
  - type: apt
    components: [main]
    suites: [r36.4]
    key-id: 3C6D1FF3100C8C3ABB0869C0E6543461A9996195
    key-server: https://repo.download.nvidia.com/jetson/jetson-ota-public.asc
    url: https://repo.download.nvidia.com/jetson/common
    architectures: [arm64]

plugs:
  hardware-observe:
  opengl:
  graphics-core22:
    interface: content
    target: $SNAP/graphics
  tensorrt-libs-cuda-12:
    interface: content
    target: $SNAP/tensorrt-libs
  system-files:
    write:
      - /dev/shm/memmap_ipc_shm


apps:
  cuda-samples:
    command-chain:
      - bin/graphics-core22-wrapper
      - bin/tensorrt-libs-wrapper
    command: bin/execute_from_target_dir.sh

  all:
    command-chain:
      - bin/graphics-core22-wrapper
      - bin/tensorrt-libs-wrapper
    command: bin/execute_all.sh

parts:
  cuda-samples:
    plugin: nil
    build-packages:
      - initramfs-tools
      - nvidia-l4t-cuda
      - cuda-12-6
      - cmake
    stage-packages:
      - libgomp1
    source: https://github.com/NVIDIA/cuda-samples.git
    source-type: git
    source-tag: v12.5
    override-build: |
      set -x
      echo '/usr/local/cuda-12.6/compat' | tee -a /etc/ld.so.conf.d/000_cuda.conf
      ldconfig
      mkdir -p $CRAFT_PART_INSTALL/usr/bin
      mkdir -p $CRAFT_PART_INSTALL/opt/cuda-samples
      make -j4 -C $CRAFT_PART_BUILD/
      cp -ar $CRAFT_PART_BUILD/Samples $CRAFT_PART_BUILD/Common $CRAFT_PART_INSTALL/opt/cuda-samples
      cd $CRAFT_PART_INSTALL/opt
      for f in $(find ./cuda-samples/Samples -executable -type f | grep -v "\.[A-Za-z]*$")
      do
        ln -sf /var/snap/cuda-samples/current/$f $CRAFT_PART_INSTALL/usr/bin/$(basename $f)
      done

  cuda-samples-list:
    plugin: dump
    source: cuda-samples-list
    organize:
      cuda-samples.list: etc/

  scripts:
    plugin: dump
    source: scripts
