name: nvpmodel
summary: Sample nvpmodel apps for Tegra
description: |
  Collection of nvpmodel use-cases for Tegra platforms
version: '1.0'
confinement: strict
grade: stable

base: core22

package-repositories:
  - type: apt
    components: [main]
    suites: [r36.4]
    key-id: 3C6D1FF3100C8C3ABB0869C0E6543461A9996195
    key-server: https://repo.download.nvidia.com/jetson/jetson-ota-public.asc
    url: https://repo.download.nvidia.com/jetson/t234
    architectures: [arm64]
  - type: apt
    components: [main]
    suites: [r36.4]
    key-id: 3C6D1FF3100C8C3ABB0869C0E6543461A9996195
    key-server: https://repo.download.nvidia.com/jetson/jetson-ota-public.asc
    url: https://repo.download.nvidia.com/jetson/common
    architectures: [arm64]

plugs:
  hardware-observe:
  set-power-management-mode:
    interface: system-files
    write:
      - /sys/devices/system/cpu/cpu0/online
      - /sys/devices/system/cpu/cpu1/online
      - /sys/devices/system/cpu/cpu2/online
      - /sys/devices/system/cpu/cpu3/online
      - /sys/devices/system/cpu/cpu4/online
      - /sys/devices/system/cpu/cpu5/online
      - /sys/devices/system/cpu/cpufreq/policy0/scaling_max_freq
      - /sys/devices/system/cpu/cpufreq/policy4/scaling_max_freq
      - /sys/devices/system/cpu/cpufreq/policy0/scaling_min_freq
      - /sys/devices/system/cpu/cpufreq/policy4/scaling_min_freq
      - /sys/devices/platform/bus@0/17000000.gpu/tpc_pg_mask
      - /sys/devices/platform/bus@0/17000000.gpu/fbp_pg_mask
      - /sys/devices/platform/bus@0/17000000.gpu/power/control
      - /sys/devices/platform/bus@0/17000000.gpu/devfreq/17000000.gpu/max_freq
      - /sys/devices/platform/bus@0/17000000.gpu/devfreq/17000000.gpu/min_freq
      - /sys/devices/platform/17000000.gpu/devfreq_dev/available_frequencies
      - /sys/devices/platform/17000000.gpu/devfreq_dev/min_freq
      - /sys/devices/platform/17000000.gpu/devfreq_dev/max_freq
      - /sys/class/devfreq/17000000.gpu/device/of_node/compatible
      - /sys/devices/platform/bus@0/17000000.gpu/railgate_enable
      - /sys/kernel/nvpmodel_clk_cap/emc
      - /sys/kernel/debug/bpmp/debug/clk/emc/min_rate
      - /sys/kernel/debug/bpmp/debug/clk/emc/rate
      - /sys/kernel/debug/bpmp/debug/clk/emc/mrq_rate_locked

layout:
  /etc/nvpmodel.conf:
    bind-file: $SNAP_DATA/etc/nvpmodel.conf
  /var/lib/nvpmodel:
    bind: $SNAP_DATA/var/lib/nvpmodel

apps:
  nvpmodel:
    command-chain: [bin/wrapper_local]
    command: usr/sbin/nvpmodel
    plugs:
      - set-power-management-mode
  jetson-clocks-show:
    command-chain: [bin/wrapper_local]
    command: usr/bin/jetson_clocks --show
    plugs:
      - set-power-management-mode

parts:
  nvpmodel:
    plugin: nil
    stage-packages:
      - nvidia-l4t-nvpmodel
      - nvidia-l4t-core
      - nvidia-l4t-tools
      - coreutils
      - bc
  launchers:
    plugin: dump
    source: launchers/
    build-attributes: [no-patchelf]
    organize:
      '*': bin/
