name: nvpmodel
summary: Sample nvpmodel apps for Tegra
description: |
  Collection of nvpmodel use-cases for Tegra platforms
version: '1.0'
confinement: strict
grade: stable

base: core22

package-repositories:
  - type: apt
    components: [main]
    suites: [r36.4]
    key-id: 3C6D1FF3100C8C3ABB0869C0E6543461A9996195
    key-server: https://repo.download.nvidia.com/jetson/jetson-ota-public.asc
    url: https://repo.download.nvidia.com/jetson/t234
    architectures: [arm64]
  - type: apt
    components: [main]
    suites: [r36.4]
    key-id: 3C6D1FF3100C8C3ABB0869C0E6543461A9996195
    key-server: https://repo.download.nvidia.com/jetson/jetson-ota-public.asc
    url: https://repo.download.nvidia.com/jetson/common
    architectures: [arm64]

plugs:
  shutdown:
  dbus-consumer:
    interface: dbus
    bus: system
    name: org.freedesktop.login1
  hardware-observe:
  set-power-management-mode:
    interface: system-files
    write:
      - /etc/nvpmodel.conf
      - /sys/power/state
      - /sys/devices/system/cpu/cpu0/online
      - /sys/devices/system/cpu/cpu1/online
      - /sys/devices/system/cpu/cpu2/online
      - /sys/devices/system/cpu/cpu3/online
      - /sys/devices/system/cpu/cpu4/online
      - /sys/devices/system/cpu/cpu5/online
      - /sys/devices/system/cpu/cpu6/online
      - /sys/devices/system/cpu/cpu7/online
      - /sys/devices/system/cpu/cpufreq/policy0/scaling_governor
      - /sys/devices/system/cpu/cpufreq/policy4/scaling_governor
      - /sys/devices/system/cpu/cpufreq/policy0/scaling_max_freq
      - /sys/devices/system/cpu/cpufreq/policy4/scaling_max_freq
      - /sys/devices/system/cpu/cpufreq/policy0/scaling_min_freq
      - /sys/devices/system/cpu/cpufreq/policy4/scaling_min_freq
      - /sys/devices/system/cpu/cpufreq/schedutil/rate_limit_us
      - /sys/devices/platform/bus@0/17000000.gpu/tpc_pg_mask
      - /sys/devices/platform/bus@0/17000000.gpu/fbp_pg_mask
      - /sys/devices/platform/bus@0/17000000.gpu/power/control
      - /sys/devices/platform/bus@0/17000000.gpu/devfreq/17000000.gpu/max_freq
      - /sys/devices/platform/bus@0/17000000.gpu/devfreq/17000000.gpu/min_freq
      - /sys/devices/platform/17000000.gpu/devfreq_dev/available_frequencies
      - /sys/devices/platform/17000000.gpu/devfreq_dev/min_freq
      - /sys/devices/platform/17000000.gpu/devfreq_dev/max_freq
      - /sys/class/devfreq/17000000.gpu/device/of_node/compatible
      - /sys/devices/platform/bus@0/17000000.gpu/railgate_enable
      - /sys/kernel/nvpmodel_clk_cap/emc
      - /sys/kernel/debug/bpmp/debug/clk/emc/min_rate
      - /sys/kernel/debug/bpmp/debug/clk/emc/rate
      - /sys/kernel/debug/bpmp/debug/clk/emc/mrq_rate_locked
      - /sys/devices/platform/bus@0/c240000.i2c/i2c-1/1-0040/hwmon/hwmon3/samples
      - /sys/devices/platform/bus@0/c240000.i2c/i2c-1/1-0040/hwmon/hwmon3/update_interval
      - /sys/devices/platform/bus@0/c240000.i2c/i2c-1/1-0040/hwmon/hwmon3/curr1_max
      - /sys/devices/platform/bus@0/c240000.i2c/i2c-1/1-0040/hwmon/hwmon3/curr1_crit
      - /sys/devices/platform/bus@0/13e00000.host1x
      - /sys/kernel/debug/tegra-host1x/actmon
      - /sys/kernel/debug/clk/dla0_core/clk_min_rate
      - /sys/kernel/debug/clk/dla0_core/clk_max_rate
      - /sys/kernel/debug/clk/dla0_core/clk_rate
      - /sys/kernel/debug/clk/dla0_falcon/clk_min_rate
      - /sys/kernel/debug/clk/dla0_falcon/clk_max_rate
      - /sys/kernel/debug/clk/dla0_falcon/clk_rate
      - /sys/kernel/debug/clk/dla1_core/clk_min_rate
      - /sys/kernel/debug/clk/dla1_core/clk_max_rate
      - /sys/kernel/debug/clk/dla1_core/clk_rate
      - /sys/kernel/debug/clk/dla1_falcon/clk_min_rate
      - /sys/kernel/debug/clk/dla1_falcon/clk_max_rate
      - /sys/kernel/debug/clk/dla1_falcon/clk_rate
      - /sys/kernel/debug/clk/pva0_vps/clk_min_rate
      - /sys/kernel/debug/clk/pva0_vps/clk_max_rate
      - /sys/kernel/debug/clk/pva0_vps/clk_rate
      - /sys/kernel/debug/clk/pva0_cpu_axi/clk_min_rate
      - /sys/kernel/debug/clk/pva0_cpu_axi/clk_max_rate
      - /sys/kernel/debug/clk/pva0_cpu_axi/clk_rate

slots:
  dbus-provider:
    interface: dbus
    bus: system
    name: org.freedesktop.login1

layout:
  /etc/nvpmodel:
    bind: $SNAP/etc/nvpmodel
  /var/lib/nvpmodel:
    bind: $SNAP_DATA/var/lib/nvpmodel

apps:
  nvpower-service:
    command-chain: [bin/wrapper_local]
    command: etc/systemd/nvpower.sh
    daemon: simple
    restart-condition: on-failure
    plugs:
      - set-power-management-mode
  nvpmodel-service:
    command-chain: [bin/wrapper_local]
    command: usr/sbin/nvpmodel -f /etc/nvpmodel.conf
    daemon: simple
    restart-condition: on-failure
    plugs:
      - set-power-management-mode
  nvpmodel:
    command-chain: [bin/wrapper_local]
    command: usr/sbin/nvpmodel
    environment:
      PYTHONPATH: $SNAP/usr/lib/python3/dist-packages:$PYTHONPATH
    plugs:
      - set-power-management-mode
      - shutdown
      - dbus-consumer
  jetson-clocks-show:
    command-chain: [bin/wrapper_local]
    command: usr/bin/jetson_clocks --show
    plugs:
      - set-power-management-mode

parts:
  nvpmodel:
    plugin: nil
    stage-packages:
      - nvidia-l4t-nvpmodel
      - nvidia-l4t-core
      - nvidia-l4t-tools
      - coreutils
      - systemd
      - bc
  reboot:
    plugin: dump
    source: .
    organize:
      reboot.py: usr/sbin/reboot
    stage-packages:
      - python3-dbus
  launchers:
    plugin: dump
    source: launchers/
    build-attributes: [no-patchelf]
    organize:
      '*': bin/
