name: vpi-samples
base: core24
version: 4.1.3
summary: NVIDIA VPI samples
description: |
  This snap contains the VPI samples.

grade: stable
confinement: strict

plugs:
  hardware-observe:
  opengl:
  gpu-2404:
    interface: content
    target: $SNAP/gpu-2404
  vpi4-core24:
    interface: content
    target: $SNAP/vpi
  system-files:
    read:
      - /proc/driver/nvidia/gpus

package-repositories:
  - type: apt
    path: /
    key-id: EB693B3035CD5710E231E123A4B469963BF863CC
    url: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2404/sbsa
  - type: apt
    components: [main]
    suites: [r39.2]
    key-id: 3C6D1FF3100C8C3ABB0869C0E6543461A9996195
    key-server: https://repo.download.nvidia.com/jetson/jetson-ota-public.asc
    url: https://repo.download.nvidia.com/jetson/som
    architectures: [arm64]
  - type: apt
    components: [main]
    suites: [r39.2]
    key-id: 3C6D1FF3100C8C3ABB0869C0E6543461A9996195
    key-server: https://repo.download.nvidia.com/jetson/jetson-ota-public.asc
    url: https://repo.download.nvidia.com/jetson/common
    architectures: [arm64]

parts:
  vpi-headers:
    plugin: nil
    source: https://developer.nvidia.com/downloads/embedded/L4T/r39_Release_v2.0/sources/public_sources.tbz2
    source-type: tar
    override-pull: |
      craftctl default
      mkdir -p $CRAFT_PART_SRC/nvsci_headers
      tar -xf $CRAFT_PART_SRC/source/nvsci_headers.tbz2 -C $CRAFT_PART_SRC/nvsci_headers
      cp $CRAFT_PART_SRC/nvsci_headers/*.h /usr/include/
    prime:
      - -*


  vpi-samples:
    after: [vpi-headers]
    plugin: nil
    build-packages:
      - cuda-13-2
      - nvidia-vpi
      - libnvvpi4
      - python3.12-vpi4
      - vpi4-samples
      - vpi4-dev
      - libopencv-dev
      - libopencv
      - cmake
      - python3-numpy
      - python3-pil
      - libopencv-python
      - libicu74
      - libegl1
    stage-packages:
      - vpi4-samples
      - libopencv-python
      - python3.12-vpi4
      - python3-numpy
      - python3-pil
    override-build: |
      mkdir -p /opt/nvidia/l4t-packages/
      touch /opt/nvidia/l4t-packages/.nv-l4t-disable-boot-fw-update-in-preinstall
      L4T_DEB_PACKAGES_PATH=${L4T_DEB_PACKAGES_PATH:="NVIDIA_ARCHIVE"}
      if [ "$L4T_DEB_PACKAGES_PATH" = "NVIDIA_ARCHIVE" ]; then
        apt update
        apt install --yes nvidia-l4t-cuda nvidia-l4t-pva nvidia-l4t-3d-core nvidia-l4t-multimedia nvidia-l4t-multimedia-utils nvidia-l4t-jetson-multimedia-api
        # just needed for linking, doesn't matter if being built on Thor or not
        apt install --yes nvidia-l4t-cuda-openrm
      elif [ -d $L4T_DEB_PACKAGES_PATH ]; then
        apt install -y libegl1 nvme-cli efibootmgr bridge-utils libffi7 libasound2 libgles2 -f
        apt install -y alsa-topology-conf alsa-ucm-conf libasound2-data libdrm-amdgpu1 -f
        apt install -y libgstreamer-plugins-bad1.0-0 libllvm15 libvulkan1 mesa-vulkan-drivers -f
        dpkg -i $L4T_DEB_PACKAGES_PATH/nvidia-l4t-core_*.deb
        dpkg -i $L4T_DEB_PACKAGES_PATH/nvidia-l4t-cuda_*.deb
        # just needed for linking
        dpkg -i $L4T_DEB_PACKAGES_PATH/nvidia-l4t-cuda-openrm_*.deb
        dpkg -i $L4T_DEB_PACKAGES_PATH/nvidia-l4t-firmware_*.deb
        dpkg -i $L4T_DEB_PACKAGES_PATH/nvidia-l4t-init_*.deb
        dpkg -i $L4T_DEB_PACKAGES_PATH/nvidia-l4t-libwayland-client0_*.deb
        dpkg -i $L4T_DEB_PACKAGES_PATH/nvidia-l4t-libwayland-server0_*.deb
        dpkg -i $L4T_DEB_PACKAGES_PATH/nvidia-l4t-nvsci_*.deb
        dpkg -i $L4T_DEB_PACKAGES_PATH/nvidia-l4t-x11_*.deb
        dpkg -i $L4T_DEB_PACKAGES_PATH/nvidia-l4t-pva_*.deb
        dpkg -i $L4T_DEB_PACKAGES_PATH/nvidia-l4t-multimedia-utils_*.deb
        dpkg -i $L4T_DEB_PACKAGES_PATH/nvidia-l4t-wayland_*.deb
        dpkg -i $L4T_DEB_PACKAGES_PATH/nvidia-l4t-3d-core_*.deb
        dpkg -i $L4T_DEB_PACKAGES_PATH/nvidia-l4t-multimedia_*.deb
        dpkg -i $L4T_DEB_PACKAGES_PATH/nvidia-l4t-multimedia-utils_*.deb
        dpkg -i $L4T_DEB_PACKAGES_PATH/nvidia-l4t-jetson-multimedia-api*.deb
      fi
      echo '/usr/local/cuda-13.2/compat' | tee -a /etc/ld.so.conf.d/000_cuda.conf
      ldconfig
      unset LD_LIBRARY_PATH
      cd $CRAFT_PART_INSTALL/opt/nvidia/vpi4/samples/
      CMAKE_OPTS="-DOpenCV_DIR=/usr/lib/cmake/opencv4 -DNvBuffer_INCLUDE_DIR=/usr/src/jetson_multimedia_api/include -DNvSci_INCLUDE_DIR=/usr/src/jetson_multimedia_api/include -DCMAKE_CUDA_COMPILER=/usr/local/cuda/bin/nvcc"
      for f in */CMakeLists.txt ; do pushd $(dirname $f) ; cmake $CMAKE_OPTS . && LD_LIBRARY_PATH=/opt/nvidia/l4t-gpu-libs/openrm VERBOSE=1 make -j 2 || echo "Skipping $(dirname $f) - build failed" ; popd ; done
      for f in */CMakeLists.txt ; do pushd $(dirname $f) ; rm -fr CMakeFiles ; popd ; done
    override-prime: |
      craftctl default
      rm -fr $CRAFT_PRIME/usr/share/icons
  vpi-wrappers:
    after: [vpi-samples]
    source: .
    plugin: dump
    organize:
      '*': bin/
    prime:
    - bin/vpi-wrapper
    - bin/gpu-2404-wrapper

apps:
  vpi-sample-01-convolve-2d:
    command-chain:
      - bin/gpu-2404-wrapper
      - bin/vpi-wrapper
    command: /opt/nvidia/vpi4/samples/01-convolve_2d/vpi_sample_01_convolve_2d
  vpi-sample-02-stereo-disparity:
    command-chain:
      - bin/gpu-2404-wrapper
      - bin/vpi-wrapper
    command: /opt/nvidia/vpi4/samples/02-stereo_disparity/vpi_sample_02_stereo_disparity
  vpi-sample-03-harris-corners:
    command-chain:
      - bin/gpu-2404-wrapper
      - bin/vpi-wrapper
    command: /opt/nvidia/vpi4/samples/03-harris_corners/vpi_sample_03_harris_corners
  vpi-sample-04-rescale:
    command-chain:
      - bin/gpu-2404-wrapper
      - bin/vpi-wrapper
    command: /opt/nvidia/vpi4/samples/04-rescale/vpi_sample_04_rescale
  vpi-sample-05-benchmark:
    command-chain:
      - bin/gpu-2404-wrapper
      - bin/vpi-wrapper
    command: /opt/nvidia/vpi4/samples/05-benchmark/vpi_sample_05_benchmark
  vpi-sample-06-klt-tracker:
    command-chain:
      - bin/gpu-2404-wrapper
      - bin/vpi-wrapper
    command: /opt/nvidia/vpi4/samples/06-klt_tracker/vpi_sample_06_klt_tracker
  vpi-sample-07-fft:
    command-chain:
      - bin/gpu-2404-wrapper
      - bin/vpi-wrapper
    command: /opt/nvidia/vpi4/samples/07-fft/vpi_sample_07_fft
  vpi-sample-08-cross-aarch64-l4t:
    command-chain:
      - bin/gpu-2404-wrapper
      - bin/vpi-wrapper
    command: /opt/nvidia/vpi4/samples/08-cross_aarch64_l4t/vpi_sample_08_cross_aarch64_l4t
  vpi-sample-09-tnr:
    command-chain:
      - bin/gpu-2404-wrapper
      - bin/vpi-wrapper
    command: /opt/nvidia/vpi4/samples/09-tnr/vpi_sample_09_tnr
  vpi-sample-10-perspwarp:
    command-chain:
      - bin/gpu-2404-wrapper
      - bin/vpi-wrapper
    command: /opt/nvidia/vpi4/samples/10-perspwarp/vpi_sample_10_perspwarp
  vpi-sample-11-fisheye:
    command-chain:
      - bin/gpu-2404-wrapper
      - bin/vpi-wrapper
    command: /opt/nvidia/vpi4/samples/11-fisheye/vpi_sample_11_fisheye
  vpi-sample-12-optflow-lk:
    command-chain:
      - bin/gpu-2404-wrapper
      - bin/vpi-wrapper
    command: /opt/nvidia/vpi4/samples/12-optflow_lk/vpi_sample_12_optflow_lk
  vpi-sample-13-optflow-dense:
    command-chain:
      - bin/gpu-2404-wrapper
      - bin/vpi-wrapper
    command: /opt/nvidia/vpi4/samples/13-optflow_dense/vpi_sample_13_optflow_dense
  vpi-sample-14-background-subtractor:
    command-chain:
      - bin/gpu-2404-wrapper
      - bin/vpi-wrapper
    command: /opt/nvidia/vpi4/samples/14-background_subtractor/vpi_sample_14_background_subtractor
  vpi-sample-15-image-view:
    command-chain:
      - bin/gpu-2404-wrapper
      - bin/vpi-wrapper
    command: /opt/nvidia/vpi4/samples/15-image_view/vpi_sample_15_image_view
  vpi-sample-17-template-matching:
    command-chain:
      - bin/gpu-2404-wrapper
      - bin/vpi-wrapper
    command: /opt/nvidia/vpi4/samples/17-template_matching/vpi_sample_17_template_matching
  vpi-sample-18-orb-feature-detector:
    command-chain:
      - bin/gpu-2404-wrapper
      - bin/vpi-wrapper
    command: /opt/nvidia/vpi4/samples/18-orb_feature_detector/vpi_sample_18_orb_feature_detector
  vpi-sample-19-dcf-tracker:
    command-chain:
      - bin/gpu-2404-wrapper
      - bin/vpi-wrapper
    command: /opt/nvidia/vpi4/samples/19-dcf_tracker/vpi_sample_19_dcf_tracker
  vpi-blur:
    command-chain:
      - bin/gpu-2404-wrapper
      - bin/vpi-wrapper
    command: /opt/nvidia/vpi4/samples/tutorial_blur/vpi_blur

