name: vpi-runtime
base: core22
version: 3.2.4-1
summary: NVIDIA VPI runtime libraries
description: |
  This snap contains the VPI runtime libraries contained in the deb
  packages nvidia-vpi, libnvvpi3 and python3.10-vpi3 from nvidia's 
  repositories.

grade: stable
confinement: strict

package-repositories:
  - type: apt
    components: [main]
    suites: [r36.4]
    key-id: 3C6D1FF3100C8C3ABB0869C0E6543461A9996195
    key-server: https://repo.download.nvidia.com/jetson/jetson-ota-public.asc
    url: https://repo.download.nvidia.com/jetson/t234
    architectures: [arm64]
  - type: apt
    components: [main]
    suites: [r36.4]
    key-id: 3C6D1FF3100C8C3ABB0869C0E6543461A9996195
    key-server: https://repo.download.nvidia.com/jetson/jetson-ota-public.asc
    url: https://repo.download.nvidia.com/jetson/common
    architectures: [arm64]
  - type: apt
    ppa: ubuntu-tegra/updates

parts:
  vpi-runtime:
    plugin: nil
    override-stage: |
      L4T_DEB_PACKAGES_PATH=${L4T_DEB_PACKAGES_PATH:="NVIDIA_ARCHIVE"}
      if [ "$L4T_DEB_PACKAGES_PATH" = "NVIDIA_ARCHIVE" ]; then
        apt update
        apt download nvidia-l4t-core nvidia-l4t-cuda nvidia-l4t-nvsci nvidia-l4t-pva nvidia-l4t-multimedia nvidia-l4t-multimedia-utils nvidia-l4t-3d-core
        debian_packages=$(find . -name "nvidia-l4t*.deb")
      elif [ -d $L4T_DEB_PACKAGES_PATH ]; then
        debian_packages="$(find $L4T_DEB_PACKAGES_PATH\
        -name "nvidia-l4t-core_*.deb" -o\
        -name "nvidia-l4t-cuda_*.deb" -o\
        -name "nvidia-l4t-3d-core_*.deb" -o\
        -name "nvidia-l4t-nvsci_*.deb" -o\
        -name "nvidia-l4t-pva_*.deb" -o\
        -name "nvidia-l4t-multimedia_*.deb" -o\
        -name "nvidia-l4t-multimedia-utils_*.deb")"
      fi
      if [[ ! -z $debian_packages ]]; then
        readarray -t <<<$debian_packages
        for f in "${MAPFILE[@]}"
        do
          echo "extracting: $f..."
          dpkg -x $f $CRAFT_PART_INSTALL/
        done
      fi
      craftctl default
    stage-packages:
      - libopencv
      - libopencv-python
      - nvidia-vpi
      - libnvvpi3
      - python3.10-vpi3
      - libegl1
    override-prime: |
      craftctl default
      rm -fr $CRAFT_PRIME/usr/share/icons

  scripts:
    plugin: dump
    source: .

slots:
  vpi3-core22:
    interface: content
    read: [$SNAP]

