name: tensorrt-samples # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '10.3.0.30-1+cuda12.5' # just for humans, typically '1.2+git' or '1.3.2'
summary: Tensorrt sample applications # 79 char long summary
description: |
  Tensorrt sample applications to test the GPU

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

package-repositories:
  - type: apt
    components: [main]
    suites: [r36.4]
    key-id: 3C6D1FF3100C8C3ABB0869C0E6543461A9996195
    key-server: https://repo.download.nvidia.com/jetson/jetson-ota-public.asc
    url: https://repo.download.nvidia.com/jetson/t234
    architectures: [arm64]
  - type: apt
    components: [main]
    suites: [r36.4]
    key-id: 3C6D1FF3100C8C3ABB0869C0E6543461A9996195
    key-server: https://repo.download.nvidia.com/jetson/jetson-ota-public.asc
    url: https://repo.download.nvidia.com/jetson/common
    architectures: [arm64]

plugs:
  hardware-observe:
  opengl:
  graphics-core22:
    interface: content
    target: $SNAP/graphics
  tensorrt-libs-cuda-12:
    interface: content
    target: $SNAP/tensorrt-libs

apps:
  tensorrt-samples:
    command-chain:
      - bin/graphics-core22-wrapper
      - bin/tensorrt-libs-wrapper
    command: bin/execute_sample.sh
    environment:
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/local/cuda-12.6/targets/aarch64-linux/lib

parts:
  tensorrt-samples:
    plugin: nil
    build-packages:
      - initramfs-tools
      - cuda-12-6
      - nvidia-l4t-dla-compiler
        #- libnvinfer-bin
      - libnvinfer-samples
    stage-packages:
      - libnvinfer-samples
    override-build: |
      echo '/usr/local/cuda-12.6/compat' | tee -a /etc/ld.so.conf.d/000_cuda.conf
      ldconfig
      cd $CRAFT_PART_INSTALL/usr/src/tensorrt/samples
      make
    override-prime: |
      mkdir -p $CRAFT_PRIME/usr/src
      cp -r $CRAFT_STAGE/usr/src/tensorrt $CRAFT_PRIME/usr/src

  tensorrt-samples-list:
    plugin: dump
    source: tensorrt-samples-list
    organize:
      tensorrt-samples.list: etc/

  scripts:
    plugin: dump
    source: scripts
