name: tensorrt-samples # you probably want to 'snapcraft register <name>'
base: core24 # the base snap is the execution environment for this snap
version: '11.0.0.114-1+cuda13.2' # just for humans, typically '1.2+git' or '1.3.2'
summary: Tensorrt sample applications # 79 char long summary
description: |
  Tensorrt sample applications to test the GPU

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

package-repositories:
  - type: apt
    components: [main]
    suites: [r39.2]
    key-id: 3C6D1FF3100C8C3ABB0869C0E6543461A9996195
    key-server: https://repo.download.nvidia.com/jetson/jetson-ota-public.asc
    url: https://repo.download.nvidia.com/jetson/som
    architectures: [arm64]
  - type: apt
    components: [main]
    suites: [r39.2]
    key-id: 3C6D1FF3100C8C3ABB0869C0E6543461A9996195
    key-server: https://repo.download.nvidia.com/jetson/jetson-ota-public.asc
    url: https://repo.download.nvidia.com/jetson/common
    architectures: [arm64]

plugs:
  hardware-observe:
  opengl:
  microstack-support:
  graphics-core22:
    interface: content
    target: $SNAP/graphics
  tensorrt-libs-cuda-13:
    interface: content
    target: $SNAP/tensorrt-libs

apps:
  tensorrt-samples:
    command-chain:
      - bin/graphics-core22-wrapper
      - bin/tensorrt-libs-wrapper
    command: bin/execute_sample.sh
      # environment:
      #   LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/local/cuda-12.6/targets/aarch64-linux/lib

layout:
  # # the path of libcudadevrt.a is determined at build time
  # /usr/local/cuda-13.2/lib64/libcudadevrt.a:
  #   symlink: $SNAP/tensorrt-libs/usr/local/cuda-13.2/targets/sbsa-linux/lib/libcudadevrt.a
  # # the path of libdevice.10.bc is determined at build time
  # /usr/local/cuda-13.2/nvvm/libdevice/libdevice.10.bc:
  #   symlink: $SNAP/tensorrt-libs/usr/local/cuda-13.2/nvvm/libdevice/libdevice.10.bc
  /usr/local/cuda/targets/sbsa-linux/lib:
    symlink: $SNAP/tensorrt-libs/usr/local/cuda-13.2/lib64
  /usr/local/cuda-13.2/lib64:
    symlink: $SNAP/tensorrt-libs/usr/local/cuda-13.2/lib64

parts:
  tensorrt-samples:
    plugin: nil
    source: https://github.com/NVIDIA/TensorRT.git
    source-type: git
    source-tag: release/11.0
    build-snaps:
      - cmake
    build-packages:
      - initramfs-tools
      - cuda-13-2
      - tensorrt
      - unzip
      - wget
        # - python3-virtualenv
        # - python3-pip
        #- libnvinfer-bin
        # - libnvinfer-samples
        # stage-packages:
        #   - libnvinfer-samples
    override-build: |
      # mkdir -p /opt/nvidia/l4t-packages/
      # touch /opt/nvidia/l4t-packages/.nv-l4t-disable-boot-fw-update-in-preinstall
      # L4T_DEB_PACKAGES_PATH=${L4T_DEB_PACKAGES_PATH:="NVIDIA_ARCHIVE"}
      # if [ "$L4T_DEB_PACKAGES_PATH" = "NVIDIA_ARCHIVE" ]; then
      #   apt update
      #   apt install --yes nvidia-l4t-dla-compiler nvidia-l4t-cuda
      # elif [ -d $L4T_DEB_PACKAGES_PATH ]; then
      #   apt install --yes libegl1 -f
      #   dpkg -i $L4T_DEB_PACKAGES_PATH/nvidia-l4t-cuda_*.deb
      #   # nvidia-l4t-dla-compiler is not part of the private set of Nvidia packages,
      #   # that's why it is installed through the Nvidia archive.
      #   apt install --yes nvidia-l4t-dla-compiler
      # fi
      # echo '/usr/local/cuda-12.6/compat' | tee -a /etc/ld.so.conf.d/000_cuda.conf
      # ldconfig
      # cd $CRAFT_PART_INSTALL/usr/src/tensorrt/samples
      # make

      # CMake 3.31 or higher is required for TensorRT 11
      # But the latest CMake for Ubuntu 24.04 LTS is 3.28.3
      # Lets upgrade it with pip just to build these samples
      # sudo DEBIAN_FRONTEND=noninteractive apt install -y python3-virtualenv python3-pip
      # virtualenv .venv && source .venv/bin/activate
      # pip install --upgrade cmake
      # Re-scan the system with the new Cmake
      # hash -r && cmake --version
      mkdir build
      cd build
      cmake .. \
          -DCMAKE_CUDA_COMPILER=/usr/local/cuda-13.2/bin/nvcc  \
          -DTRT_LIB_DIR=/usr/lib/aarch64-linux-gnu \
          -DTRT_OUT_DIR=`pwd`/bin \
          -DBUILD_SAMPLES=ON \
          -DBUILD_PARSERS=OFF \
          -DBUILD_PLUGINS=OFF \
          -DTRT_PLATFORM_ID=aarch64
      cmake --build . --parallel $(nproc)
      mkdir -p $CRAFT_PART_INSTALL/usr/src/tensorrt/samples/
      cp -ar samples/ $CRAFT_PART_INSTALL/usr/src/tensorrt
      cp -ar bin/ $CRAFT_PART_INSTALL/usr/src/tensorrt

      echo "Fetching tensorrt_sample_data URL"
      if ! wget -q https://raw.githubusercontent.com/NVIDIA/TensorRT/main/samples/README.md; then
        echo "Error: failed to fetch the tensorrt_sample_data URL"
        exit 1
      fi
      sample_data_url=$(grep -o "https://github.com/NVIDIA/TensorRT/releases/download/.*zip" README.md)
      if [ -z "$sample_data_url" ]; then
        echo "Error: sample_data_url is empty"
        exit 1
      fi
      echo "Downloading tensorrt_sample_data"
      if ! wget -q $sample_data_url; then
        echo "Error: failed to download the tensorrt_sample_data"
        rm -rf README.md
        exit 1
      fi
      echo "Installing the TensorRT sample_data"
      unzip tensorrt_sample_data_*.zip -d $CRAFT_PART_INSTALL/usr/src/tensorrt/data

    override-prime: |
      mkdir -p $CRAFT_PRIME/usr/src
      cp -r $CRAFT_STAGE/usr/src/tensorrt $CRAFT_PRIME/usr/src

  tensorrt-samples-list:
    plugin: dump
    source: tensorrt-samples-list
    organize:
      tensorrt-samples.list: etc/

  scripts:
    plugin: dump
    source: scripts
