name: nvidia-tegra-runtime # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '36.4' # just for humans, typically '1.2+git' or '1.3.2'
summary: NVIDIA Tegra firmware and core files for Jetson and IGX ORIN boards (arm64) # 79 char long summary
description: |
  Install all necessary files to run CUDA toolkit on Ubuntu image

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  nvidia-smi:
    command: usr/sbin/nvidia-smi
    environment:
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib/aarch64-linux-gnu/nvidia/
    plugs:
      - hardware-observe
      - opengl

package-repositories:
  - type: apt
    components: [main]
    suites: [r36.4]
    key-id: 3C6D1FF3100C8C3ABB0869C0E6543461A9996195
    key-server: https://repo.download.nvidia.com/jetson/jetson-ota-public.asc
    url: https://repo.download.nvidia.com/jetson/t234
    architectures: [arm64]
  - type: apt
    components: [main]
    suites: [r36.4]
    key-id: 3C6D1FF3100C8C3ABB0869C0E6543461A9996195
    key-server: https://repo.download.nvidia.com/jetson/jetson-ota-public.asc
    url: https://repo.download.nvidia.com/jetson/common
    architectures: [arm64]

parts:
  nvidia-tegra-runtime:
    # See 'snapcraft plugins'
    plugin: nil
    source: .
    stage-packages:
      - nvidia-l4t-nvml
      - nvidia-l4t-cuda
      - nvidia-l4t-dla-compiler
      - nvidia-l4t-graphics-demos

  scripts:
    plugin: dump
    source: scripts

slots:
  graphics-core22:
    interface: content
    read: [$SNAP]
